import pygame.font
pygame.font.init()

# Fonts:
NORMAL_FONT = pygame.font.SysFont('content/fonts/ARCADEPI.ttf', 30)
SMALL_STATUS_FONT = pygame.font.SysFont('arial', 15)
UI_FRAME_FONT = pygame.font.SysFont('arial', 11)
DEATH_FONT = pygame.font.SysFont('content/fonts/ARCADEPI.ttf', 70)
FPS_FONT = pygame.font.SysFont('content/fonts/ARCADEPI.ttf', 30)
BUTTON_FONT = pygame.font.SysFont('content/fonts/ARCADEPI.ttf', 30)

# Colors:
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREY = (219, 216, 206)
RED = (181, 11, 65)
SKY = (12, 64, 94)
YELLOW = (224, 187, 123)
BUTTON_BASIC_COLOR = (105, 77, 86)
BUTTON_ACTIVE_COLOR = (181, 11, 65)

# Game settings:
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900
RESOLUTION_SCALE = 2
TILE_SIZE = 32

# Player settings:
PLAYER_SIZE = (30, 57)
PLAYER_SPEED = 4
PLAYER_GRAVITY = 0.8
PLAYER_JUMP_SPEED = -12
PLAYER_MAX_HEALTH = 11500

PLAYER_ANIMATIONS_PATH = 'content/graphics/character/'
PLAYER_DEATH_ANIMATION_SPEED = 0.15

# Enemy settings:
ENEMY_SIZE = {'sceleton': (30, 62), 'ninja': (30, 57), 'wizard': (30, 57)}
ENEMY_SPEED = 1
ENEMY_GRAVITY = 0.8
ENEMY_ANIMATION_SPEED = 0.15


ENEMY_SCELETON_HEALTH = 225
ENEMY_NINJA_HEALTH = 120
ENEMY_WIZARD_HEALTH = 60

ENEMY_ANIMATIONS_PATH = 'content/graphics/enemies/'

# Frames Per Seconds:
FPS = 60
FPS_SHOW_POS = (60, 25)

# Buttons:
BUTTON_SIZE = (200, 40)
BUTTONS_SPACE = 40

# Attacking:
PLAYER_ATTACK_SPEED = 0.3
ATTACK_SIZE = [40, 57]
ATTACK_SPACE = 25
ENEMY_ATTACK_SPACE = 5
SWORD_ATTACKING_COOLDOWN = 1000
SHIELD_COOLDOWN = 1000
IMMUNITY_FROM_HIT = 300
SCELETON_TRIGGER_LENGTH = 100
SCELETON_ATTACK_SPEED = 0.25
NINJA_TRIGGER_LENGTH = 350
NINJA_ATTACK_SPEED = 0.15
WIZARD_TRIGGER_LENGTH = 350
WIZARD_ATTACK_SPEED = 0.25

BULLET_DEFAULT_SPEED = {'arrow': 10, 'death_bullet': 5}

# UI:
UI_ACTIVE_EQUIPMENT_POSITION = (SCREEN_WIDTH / 15, SCREEN_HEIGHT - 100)
UI_FRAME_SIZE = (80, 90)
UI_ITEM_IMAGE_SIZE = (60, 70)
UI_HP_BAR_POSITION = (20, 50)


# Developing:

SHOW_IMAGE_RECTANGLES = False
SHOW_COLLISION_RECTANGLES = True
SHOW_HIT_RECTANGLES = True

SHOW_PLAYER_STATUS = True
SHOW_ENEMY_STATUS = True
SHOW_STATUS_SPACE = 6